version: '3.3'

services:
#  backend:
#    build: ./backend
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=db
    ports:
      - 6001:5432
